version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: lireddit_postgres
    environment:
      POSTGRES_DB: lireddit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lireddit_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: lireddit_redis
    ports:
      - "6379:6379"

volumes:
  lireddit_data:
